version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: garka-test-mongo
    ports:
      - '27017:27017'
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand({ ping: 1 })']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_test_data:/data/db

volumes:
  mongo_test_data:
    driver: local
